---
- hosts: localhost 
  gather_facts: yes
  
  vars: 
    MD5CHECK_FAIL:
      - 2
      
  tasks:
  - name: Backup the config files before editing it
    shell: |  
       cp /etc/hosts /var/tmp/hosts.bak.{{ansible_date_time.date}}
       cp /etc/nsswitch.conf /var/tmp/nsswitch.conf.bak.{{ansible_date_time.date}}

  - name: Valdiate the backup files using md5 checksum 
    shell: md5sum "{{ item.orig }}" "{{ item.backup }}" | uniq | wc -l 
    with_items:
      - { orig: '/etc/hosts', backup: '/var/tmp/hosts.bak.{{ansible_date_time.date}}'}
      - { orig: '/etc/nsswitch.conf', backup: '/var/tmp/nsswitch.conf.bak.{{ansible_date_time.date}}'}
      - { orig: '/etc/nsswitch.conf', backup: '/var/tmp/hosts.bak.{{ansible_date_time.date}}'}
    register: MD5

  - fail: 
      msg: Backup files integrity is failed
    when: "{{ item.stdout }} in  MD5CHECK_FAIL"
    with_items: " {{ MD5.results }} "
